# Stable software environment for the Brightway course
# Using Brightway2 + Activity Browser, tested with ecoinvent 3.9.1
name: bw-course
channels:
  - conda-forge
dependencies:
  # Core Python version
  - python=3.10

  # Classic Brightway2 stack
  - brightway2
  - bw2io
  - bw2calc
  - bw2data

  # GUI for Brightway
  - activity-browser

  # For teaching notebooks
  - jupyterlab

  # Data analysis stack
  - numpy
  - pandas
  - matplotlib
  - seaborn
